version: '3.0'

services:
   reverseproxy:
      build:
         context: ./
         dockerfile: Dockerfile-reverse-proxy
      volumes:
         - ./reverseproxy/nginx/html:/usr/share/nginx/html
      ports:
         - 80:80
         - 443:443
      networks:
         - dominionet
      depends_on:
         - dominiohost

   dominiobuilder:
      build:
         context: ./app-api
         dockerfile: Dockerfile-dominio-builder
      volumes:
         - dominiopublish:/publish  

   dominiohost:
      build:
         context: ./app-api
         dockerfile: Dockerfile-dominio-host
      volumes:
         - dominiopublish:/app
      depends_on:
         - dominiobuilder
      networks:
         - dominionet

volumes:
   dominiopublish:

networks:
   dominionet:
