version: '3.0'

services:
   reverseproxy:
      build:
         context: ./
         dockerfile: Dockerfile-reverse-proxy
      volumes:
         - ./reverseproxy/nginx/html:/usr/share/nginx/html
      ports:
         - 80:80
         - 443:443
