version: '3.0'

services:
   reverseproxy:
      build:
         context: ./
         dockerfile: Dockerfile-reverse-proxy
      volumes:
         - ./reverseproxy/nginx/html:/usr/share/nginx/html
      ports:
         - 80:80
         - 443:443
      networks:
         - dominionet
      depends_on:
         - dominiohost

   dominiobuilder:
      build:
         context: ./app-api
         dockerfile: Dockerfile-dominio-builder
      depends_on:
            - dominiodb
      volumes:
         - dominiopublish:/publish  

   dominiohost:
      build:
         context: ./app-api
         dockerfile: Dockerfile-dominio-host
      volumes:
         - dominiopublish:/app
      depends_on:
         - dominiobuilder
         - dominiodb
      networks:
         - dominionet

   dominiodb:
      image: postgres:10-alpine
      environment:
            - POSTGRES_PASSWORD=teste123
            - PGDATA=/datas/dominio-postgres/
      networks:
            - dominionet
      volumes:
            - /datas/dominio-postgres/:/datas/dominio-postgres/

volumes:
   dominiopublish:

networks:
   dominionet:
