export const actionsTypes = {
  AUTHENTICATE_START: 'AUTHENTICATE_START',
  AUTHENTICATE_ERROR: 'AUTHENTICATE_ERROR',
  AUTHENTICATE_DONE: 'AUTHENTICATE_DONE',
  LOGOUT: 'LOGOUT',
  CREATING_USER: 'CREATING_USER',
  USER_CREATED: 'USER_CREATED',
  CREATE_USER_ERROR: 'CREATE_USER_ERROR'
};

